"""Pydantic models for structured agent outputs."""
from __future__ import annotations

from pydantic import BaseModel, Field


class DailyBriefing(BaseModel):
    """Structured daily briefing generated by the ProductivityCoordinator."""

    daily_summary: str = Field(
        description="High-level summary of today's priorities and context."
    )
    important_emails: list[str] = Field(
        default_factory=list,
        description="Emails requiring attention, as short action-item strings.",
    )
    pending_tasks: list[str] = Field(
        default_factory=list,
        description="Pending tasks ordered by priority.",
    )
    knowledge_base_highlights: list[str] = Field(
        default_factory=list,
        description="Key insights or topics surfaced from the knowledge base / notes.",
    )
    latest_research: list[str] = Field(
        default_factory=list,
        description="Recent AI/tech trends or research highlights.",
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Actionable recommendations for making the most of today.",
    )
    next_actions: list[str] = Field(
        default_factory=list,
        description="Specific, ordered next steps the user should take right now.",
    )

    def to_text(self) -> str:
        """Render briefing as plain text for download."""
        from datetime import date

        lines = [
            f"# 🧠 Daily Briefing — {date.today().strftime('%A, %B %d %Y')}",
            "",
            "## 📌 Summary",
            self.daily_summary,
            "",
        ]

        def _section(title: str, items: list[str]) -> list[str]:
            if not items:
                return []
            return [f"## {title}", *[f"- {i}" for i in items], ""]

        lines += _section("📧 Important Emails", self.important_emails)
        lines += _section("✅ Pending Tasks", self.pending_tasks)
        lines += _section("📚 Knowledge Base Highlights", self.knowledge_base_highlights)
        lines += _section("🔬 Latest Research", self.latest_research)
        lines += _section("💡 Recommendations", self.recommendations)
        lines += _section("🚀 Next Actions", self.next_actions)

        return "\n".join(lines)
